export const ActionTypes = {
  // product Reducer
  FETCH_PRODUCTS : 'FETCH_PRODUCTS',
  SET_ALL_PRODUCTS: 'SET_ALL_PRODUCTS',
  SET_PRODUCT_TYPE: 'SET_PRODUCT_TYPE',
  // category Reducer
  SET_CATEGORIES : 'SET_CATEGORIES',
  FETCH_CATEGORIES : 'FETCH_CATEGORIES'
}